pluginManagement {
    plugins {
        id 'org.jetbrains.kotlin.jvm' version '1.8.22'
    }
}
include 'libGdxLib',
        'libGdx',
        'desktop',
        'libGdxMultDown',
        'android' ,
        'libGdxAndroid',
        "libgdxbox2d",
        "libCommon",
        "core",
        "libGdxLib3D",
        "libGdxLibTool3D",
        "libGdxJnigenLoader",
        "FontGenerator",
        "libGdxEvent",
        "tools"
