apply plugin: "java"
group='com.github.wangGame'

sourceCompatibility = 1.8
sourceSets.main.java.srcDirs = [
        "src"
]

dependencies {
    implementation project (':libGdxLib')
    implementation project (':libGdx')
    implementation project(":libGdxLib3D")
}

// 指定编码
tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}

