apply plugin: "java"
group='com.github.wangGame'

sourceCompatibility = 1.8
sourceSets.main.java.srcDirs = [
        "utilssrc"
]


// 指定编码
tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}


dependencies {
    implementation project(':libGdx')
    implementation project(":libGdxJnigenLoader")
}