apply plugin: "java"
group='com.github.wangGame'

sourceSets.main.java.srcDirs = [ "src/" ]
sourceSets.main.resources.srcDirs = ["../android/assets"]
sourceCompatibility = 1.8

project.ext.mainClassName = "com.tony.puzzle.DesktopLauncher"
project.ext.assetsDir = new File("../android/assets");


def methodTimeAgent = file(
        'libs/method-time-desktop-agent-1.1.0.jar'
)


// 给所有通过 Gradle 启动的 Java main 方法添加 Agent
tasks.withType(JavaExec).configureEach {
    jvmArgs "-javaagent:${methodTimeAgent.absolutePath}"

    doFirst {
        println "[MethodTime] agent=${methodTimeAgent.absolutePath}"
    }
}


dependencies {
    implementation files('libs/gdx-backend-lwjgl.jar')
    implementation files('libs/gdx-platform-1.13.1-natives-desktop.jar')
    implementation files('libs/gdx-tools.jar')
    implementation files('libs/gdx-PVR-0.2.1-b34.jar')
    implementation files('libs/solvitaire.jar')
    implementation project (':libGdxLib')
    implementation project (':libGdx')
    implementation project(":libCommon")
    implementation 'org.aspectj:aspectjrt:1.9.25.1'

    implementation files("libs/method-time-desktop-agent-1.1.0.jar")

    implementation project(":libGdxLib3D")
    implementation 'junit:junit:4.12'
    implementation "com.badlogicgames.gdx:gdx-freetype-platform:1.9.8:natives-desktop"
    implementation "com.badlogicgames.gdx:gdx-freetype:1.9.8"
    implementation 'com.squareup.okhttp3:okhttp:4.9.3'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
    implementation project(':libgdxbox2d')
    implementation project(":libGdxLibTool3D")
    implementation project(":libGdxEvent")
    implementation "com.kotcrab.vis:vis-ui:1.2.3"
// https://mvnrepository.com/artifact/com.badlogicgames.gdx/gdx-platform
    implementation group: 'com.badlogicgames.gdx', name: 'gdx-platform', version: '1.13.1', ext: 'pom'
// https://mvnrepository.com/artifact/com.badlogicgames.gdx/gdx-backend-lwjgl
    implementation group: 'com.badlogicgames.gdx', name: 'gdx-backend-lwjgl', version: '1.13.1'
    implementation project(':core')
    implementation "com.github.mgsx-dev.gdx-gltf:gltf:-SNAPSHOT"
}

task dist(type: Jar) {
    duplicatesStrategy(DuplicatesStrategy.EXCLUDE)
    manifest {
        attributes 'Main-Class': project.mainClassName
    }
    dependsOn configurations.runtimeClasspath
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    with jar
}
